#! /bin/bash

# log dosyasına başladı-bitti bilgisi yazılır, tarih ve saatle.
# örnek:
# yedekleme başladı	: 09.05.14-22:17:38
# yedekleme tamamlandı	: 09.05.14-22:19:14

# echo için -e argümanı, \t gibi özel karakterin kullanılmasına izin veriyor (escape)

BEKAPPATH = ~/Genel/yedekler/posta

echo -e yedekleme başladı'\t'\: `date +%d.%m.%y-%T` >> $BEKAPPATH/meyl.bekap.log

tar -cvpzf $BEKAPPATH/Evol_ydk_$(date +%Y%m%d).tar.gz ~/.local/share/evolution/*

echo -e yedekleme tamamlandı'\t'\: `date +%d.%m.%y-%T` >> $BEKAPPATH/meyl.bekap.log
echo 2 gün önceki yedek siliniyor 
sleep 3
OLDBEKAPFILE=`echo ~/Genel/yedekler/posta/Evol_ydk_$(date +%Y%m%d --date="2 days ago").tar.gz`
echo $OLDBEKAPFILE
if [ -f $OLDBEKAPFILE ]
then 
    rm -f $OLDBEKAPFILE && echo -e Silinen yedeğin tarihi'\t'\: $(date +%d.%m.%Y --date="2 days ago") >> $BEKAPPATH/meyl.bekap.log
else 
    echo Silinecek 2 gün öncesi tarihli bir dosya bulunamadı. Birşey silinmeyecek. >> $BEKAPPATH/meyl.bekap.log
fi

# if test -f /tmp/testfile.log 
# then
#    echo "File exists"
# fi

*/ 
[ -f ~/Genel/yedekler/posta/meyl.bekap.log ] && echo "File exists" || echo "Fİle no existo!"
/*

exit

# Burada (en sonda) şu ifadeyi yazıyor: 
# 2 gün önceki yedek siliniyor
# meyl.bekap.sh: satır 24: /home/basri/Genel/TB_ydk_20150425.tar.gz: Böyle bir dosya ya da dizin yok

# Silinecek 2 gün öncesi tarihli dosya var mı kontrol et:

# if [ -e veya -f "$eskiDosya" ] --> -e : file exists , -f : file is a real file
# then
#    rm $eskiDosya
#    echo -e Silinen yedeğin tarihi'\t'\: $(date +%d.%m.%Y --date="2 days ago") >> ~/Genel/backuplog
# else 
#    echo -e Silinecek 2 gün öncesi tarihli bir dosya bulunamadı. >> ~/Genel/backuplog
# fi

# Silmek için şu daha mı iyi olur?: mv TB_ydk_$(date vs vs).tar.gz /dev/null

# Feature wishlist:
# Silinen olmasa da silinen yedeğin tarihi yazıyor, dosya ancak varsa silsin. -- TAMAM
# Log dosyasında belli satır sayısına ulaştyığında baştan satır silmeye başla
# Yedekleme sonrası aynı yerdeki bir önceki/daha önceki yedek 
#+ dosyalarının silinmesi eklenecek: TAMAMDIR
# 2 gün ve 1 gün önceki yedekler korunup daha önceki tarihli 
#+ tüm yedeklerin silinmesi -- for loop olur sanırım
# 
# Kütüğün bitti bilgisinin postayla yollanması sonra eklenecek
# MAILTO=eposta@adresi.com 

# Mutlak ve göreceli yollar konusu
# Herhangi bir dizinde çalıştırma

# Kullanıcıdan girdi alıp dosya adlandırma
